### ISSUE TITLE
sequencing data not found in GEO with PRJNA995902

### ISSUE THREAD

**Issue by xieyy46** [mfurla/NanOlympicsMod#1]
Hi,
Cheers for your works! I am so intersected in your works and want to reproduce some results for practice! However, I can not found your sequencing data in GEO with PRJNA995902. Have you released these data yet? Thank you!

**Comment by mfurla** [comment]
Hi,

thank you very much for your interest in our work!

I have just released the dataset:

**HEK293T Untreated**: https://www.ncbi.nlm.nih.gov/sra/?term=SRR25412919
**HEK293T METTL3 Inhibited**: https://www.ncbi.nlm.nih.gov/sra/?term=SRR25412918

Cheers,

Mattia
